modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="http://github.com/MineLittlePony/MineLittlePony/issues/"
[[mods]]
modId="minelittlepony"
version="3.2"
displayName="Mine Little Pony"
displayURL="http://minelittlepony-mod.com/"
authors="Verdana, Rene_Z, Mumfrey, Killjoy1221, Sollace"
description='''
Mine Little Pony turns players and mobs into ponies. Press F9 ingame to access settings.
'''
[[dependencies.minelittlepony]]
    modId="hdskins"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="BEFORE"
    side="BOTH"