modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="http://github.com/MineLittlePony/MineLittlePony/issues/"
logoFile="minelp_logo.png"

[[mods]]
    modId="minelittlepony"
    version="3.2"
    displayName="Mine Little Pony"
    displayURL="http://minelittlepony-mod.com/"
    credits="Verdana, Rene_Z, Mumfrey, Killjoy1221, Sollace"
    authors="Verdana"
    description='''
Mine Little Pony turns players and mobs into ponies.

Press F9 ingame to access settings.'''

[[dependencies.minelittlepony]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.minelittlepony]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.minelittlepony]]
    modId="hdskins"
    mandatory=false
    versionRange="[5.0.0,)"
    ordering="BEFORE"
    side="BOTH"